/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Создать бронирование
         *
         *     **Валидация:**
         *     - startAt должен соответствовать сетке слотов (кратен durationMinutes)
         *     - Время должно быть в рамках OwnerSettings.workDayStart - workDayEnd
         *     - Не должно быть пересечений с существующими бронированиями (409 Conflict)
         *
         *     **Правило занятости:**
         *     На одно и то же время нельзя создать два бронирования — даже если они
         *     относятся к разным типам событий.
         */
        post: operations["PublicAPI_createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить список доступных типов событий */
        get: operations["PublicAPI_listEventTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Получить список бронирований (с фильтрами).
         *
         *     Без фильтров: возвращаются бронирования за сегодня и будущие (startAt >= startOfToday),
         *     отсортированные по startAt ASC.
         *
         *     Возвращает все бронирования, включая orphan (с удалёнными типами событий).
         */
        get: operations["OwnerAPI_listBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Отменить бронирование. Возвращает 204 No Content при успехе. */
        delete: operations["OwnerAPI_cancelBooking"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Создать тип события
         *
         *     **Ограничение:** нельзя создать более одного типа с duration=15
         *     и более одного типа с duration=30.
         *
         *     **Сид данных:** при первом запуске автоматически создаются:
         *     - "Встреча 15 минут" (15 минут)
         *     - "Встреча 30 минут" (30 минут)
         */
        post: operations["OwnerAPI_createEventType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * @description Удалить тип события. Возвращает 204 No Content при успехе.
         *
         *     **Примечание:** существующие бронирования этого типа остаются в системе
         *     (orphan bookings), но новые бронирования этого типа станут невозможны.
         */
        delete: operations["OwnerAPI_deleteEventType"];
        options?: never;
        head?: never;
        /**
         * @description Обновить тип события (частичное обновление).
         *     Длительность изменить нельзя после создания.
         */
        patch: operations["OwnerAPI_updateEventType"];
        trace?: never;
    };
    "/api/owner/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Обновить настройки владельца (частичное обновление) */
        patch: operations["OwnerAPI_updateSettings"];
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить настройки владельца (профиль, аватар, часы работы) */
        get: operations["PublicAPI_getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Получить слоты за период для выбранного типа события
         *
         *     Возвращает только будущие слоты (startAt > now()).
         *
         *     Используется дважды:
         *     - С диапазоном на весь видимый месяц (например, 2026-03-01..2026-03-31) — для отображения
         *     счётчика свободных слотов под каждым днём календаря
         *     - С диапазоном на один день (например, 2026-03-28..2026-03-28) — для отображения
         *     списка слотов справа
         */
        get: operations["PublicAPI_listSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Бронирование — запись гостя на выбранный слот */
        Booking: {
            id: string;
            /**
             * @description ID типа события.
             *     Может ссылаться на удалённый тип (orphan booking после DELETE /api/event-types/{id}).
             */
            eventTypeId: string;
            /** @description Название типа события. Сохраняется на момент создания (snapshot). */
            eventTypeName: string;
            /** @description Имя гостя */
            guestName: string;
            /** @description Email гостя */
            guestEmail: string;
            /**
             * Format: date-time
             * @description Начало бронирования
             */
            startAt: string;
            /**
             * Format: date-time
             * @description Конец бронирования
             */
            endAt: string;
            /**
             * Format: date-time
             * @description Дата создания бронирования
             */
            createdAt: string;
        };
        /** @description Ошибка: слот уже занят (пересечение с существующим бронированием) */
        ConflictError: {
            /** @enum {string} */
            error: "SLOT_ALREADY_BOOKED";
            /** @enum {string} */
            message: "Выбранный слот уже занят. Пожалуйста, выберите другое время.";
        };
        /**
         * @description Запрос на создание бронирования
         *
         *     **Валидация startAt:**
         *     - Для типа 15 минут: время должно быть кратно 15 минутам (XX:00, XX:15, XX:30, XX:45)
         *     - Для типа 30 минут: время должно быть кратно 30 минутам (XX:00, XX:30)
         *     - Время должно быть в рамках OwnerSettings.workDayStart - workDayEnd
         */
        CreateBookingRequest: {
            /** @description ID выбранного типа события */
            eventTypeId: string;
            /** @description Имя гостя */
            guestName: string;
            /** @description Email гостя */
            guestEmail: string;
            /**
             * Format: date-time
             * @description Начало выбранного слота (строго кратно durationMinutes типа)
             */
            startAt: string;
        };
        /**
         * @description Запрос на создание типа события
         *
         *     **Ограничение:** нельзя создать более одного типа с duration=15
         *     и более одного типа с duration=30.
         */
        CreateEventTypeRequest: {
            name: string;
            description: string;
            /**
             * @description Длительность — только 15 или 30 минут
             * @enum {number}
             */
            durationMinutes: 15 | 30;
        };
        /** @description Ошибка: тип события с такой длительностью уже существует */
        DuplicateDurationError: {
            /** @enum {string} */
            error: "DUPLICATE_DURATION";
            /** @enum {string} */
            message: "Тип события с такой длительностью уже существует. Разрешено только по одному типу для 15 и 30 минут.";
        };
        /** @description Тип события — определяет длительность встречи (15 или 30 минут) */
        EventType: {
            id: string;
            /** @description Название типа события (например, "Встреча 15 минут", "Встреча 30 минут") */
            name: string;
            /** @description Описание типа события */
            description: string;
            /**
             * @description Длительность в минутах — только 15 или 30
             * @enum {number}
             */
            durationMinutes: 15 | 30;
        };
        /** @description Ошибка: недопустимое время слота (не кратно durationMinutes или вне рабочих часов) */
        InvalidSlotTimeError: {
            /** @enum {string} */
            error: "INVALID_SLOT_TIME";
            /** @enum {string} */
            message: "Недопустимое время начала слота. Время должно соответствовать сетке и быть в рамках рабочих часов.";
        };
        /** @description Ошибка: ресурс не найден */
        NotFoundError: {
            /** @enum {string} */
            error: "NOT_FOUND";
            message: string;
        };
        /**
         * @description Настройки владельца календаря (профиль и часы работы).
         *     Владелец один и предзадан. В API возвращается без id, маршрут всегда /api/settings.
         *     Дефолтные значения: workDayStart="09:00", workDayEnd="18:00".
         */
        OwnerSettings: {
            /** @description Имя владельца (отображается гостям) */
            name: string;
            /** @description URL аватара владельца */
            avatarUrl?: string;
            /** @description Начало рабочего дня. Формат: HH:mm, 24-часовой, например "09:00" */
            workDayStart: string;
            /** @description Конец рабочего дня. Формат: HH:mm, 24-часовой, например "18:00" */
            workDayEnd: string;
        };
        /** @description Слот для бронирования — временное окно для конкретного типа события */
        Slot: {
            /**
             * Format: date-time
             * @description Начало слота
             */
            startAt: string;
            /**
             * Format: date-time
             * @description Конец слота (startAt + EventType.durationMinutes)
             */
            endAt: string;
            /**
             * @description Занят ли слот любым бронированием.
             *     Только факт занятости. В PublicAPI данные о госте не возвращаются никогда.
             */
            isBooked: boolean;
        };
        /**
         * @description Запрос на обновление типа события (частичное обновление).
         *     Длительность изменить нельзя — только name и description.
         */
        UpdateEventTypeRequest: {
            name?: string;
            description?: string;
        };
        /** @description Запрос на обновление настроек владельца */
        UpdateOwnerSettingsRequest: {
            name?: string;
            avatarUrl?: string;
            workDayStart?: string;
            workDayEnd?: string;
        };
        /** @description Ошибка валидации */
        ValidationError: {
            /** @enum {string} */
            error: "VALIDATION_ERROR";
            message: string;
            details?: string[];
        };
    };
    responses: never;
    parameters: {
        /** @description Фильтр: бронирования до этой даты включительно. Формат: YYYY-MM-DD */
        "ListBookingsRequest.endDate": string;
        /** @description Фильтр по типу события */
        "ListBookingsRequest.eventTypeId": string;
        /** @description Фильтр: бронирования с этой даты. Формат: YYYY-MM-DD */
        "ListBookingsRequest.startDate": string;
        /** @description Конец периода (дата, включительно). Формат: YYYY-MM-DD, например 2026-03-31 */
        "ListSlotsRequest.endDate": string;
        /** @description ID типа события (определяет шаг сетки слотов) */
        "ListSlotsRequest.eventTypeId": string;
        /** @description Начало периода. Формат: YYYY-MM-DD, например 2026-03-01 */
        "ListSlotsRequest.startDate": string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    PublicAPI_createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Ошибка: недопустимое время слота (не кратно durationMinutes или вне рабочих часов) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidSlotTimeError"] | components["schemas"]["ValidationError"];
                };
            };
            /** @description Ошибка: ресурс не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description Ошибка: слот уже занят (пересечение с существующим бронированием) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
        };
    };
    PublicAPI_listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    OwnerAPI_listBookings: {
        parameters: {
            query?: {
                /** @description Фильтр по типу события */
                eventTypeId?: components["parameters"]["ListBookingsRequest.eventTypeId"];
                /** @description Фильтр: бронирования с этой даты. Формат: YYYY-MM-DD */
                startDate?: components["parameters"]["ListBookingsRequest.startDate"];
                /** @description Фильтр: бронирования до этой даты включительно. Формат: YYYY-MM-DD */
                endDate?: components["parameters"]["ListBookingsRequest.endDate"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    OwnerAPI_cancelBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ошибка: ресурс не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    OwnerAPI_createEventType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventTypeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description Ошибка: тип события с такой длительностью уже существует */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateDurationError"];
                };
            };
        };
    };
    OwnerAPI_deleteEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ошибка: ресурс не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    OwnerAPI_updateEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventTypeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description Ошибка: ресурс не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    OwnerAPI_updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOwnerSettingsRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerSettings"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    PublicAPI_getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerSettings"];
                };
            };
        };
    };
    PublicAPI_listSlots: {
        parameters: {
            query: {
                /** @description ID типа события (определяет шаг сетки слотов) */
                eventTypeId: components["parameters"]["ListSlotsRequest.eventTypeId"];
                /** @description Начало периода. Формат: YYYY-MM-DD, например 2026-03-01 */
                startDate: components["parameters"]["ListSlotsRequest.startDate"];
                /** @description Конец периода (дата, включительно). Формат: YYYY-MM-DD, например 2026-03-31 */
                endDate: components["parameters"]["ListSlotsRequest.endDate"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
}
